# https://taskfile.dev

version: "2"

env:
  OUT_FILE_PATH: out/image.ppm

tasks:
  build:
    cmds:
      - g++ src/main.cpp -o out/program
  run:
    cmds:
      - out/program
      - xdg-open out/image.ppm
