# https://taskfile.dev

version: "2"

env:
  OUT_FILE_PATH: out/image.ppm

tasks:
  build:
    cmds:
      - g++ -g src/main.cpp -o out/main
  run:
    cmds:
      - out/main
      - xdg-open $OUT_FILE_PATH
