# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - g++ src/main.cpp -o out/program
  run:
    cmds:
      - out/program > out/image.ppm
      - xdg-open out/image.ppm
